#!/run/initramfs/bin/ash

BUSYBOX_DIR=/run/initramfs/bin

poweroff_handler() {
    $BUSYBOX_DIR/kill -s TERM -1
    $BUSYBOX_DIR/sync
    $BUSYBOX_DIR/sleep 1

    $BUSYBOX_DIR/kill -s KILL -1
    $BUSYBOX_DIR/sync
    $BUSYBOX_DIR/sleep 1

    $BUSYBOX_DIR/umount -a -r
    $BUSYBOX_DIR/swapoff -a
    $BUSYBOX_DIR/poweroff -f
}

trap poweroff_handler 0 USR1 USR2 TERM

export $($BUSYBOX_DIR/cat /run/runx/env | $BUSYBOX_DIR/xargs)
cmd=`$BUSYBOX_DIR/cat /run/runx/cmdline`
echo "Executing $cmd..."
eval $cmd &
wait
