#!/run/initramfs/bin/ash

BUSYBOX_DIR=/run/initramfs/bin
CONFIG_DIR=/run/runx
XE_DAEMON=/usr/bin/xe-daemon

poweroff_handler() {
    $BUSYBOX_DIR/kill -s TERM -1
    $BUSYBOX_DIR/sync
    $BUSYBOX_DIR/sleep 1

    $BUSYBOX_DIR/kill -s KILL -1
    $BUSYBOX_DIR/sync
    $BUSYBOX_DIR/sleep 1

    $BUSYBOX_DIR/umount -a -r
    $BUSYBOX_DIR/swapoff -a
    $BUSYBOX_DIR/poweroff -f
}

trap '' INT
trap poweroff_handler 0 USR1 USR2 TERM

export $($BUSYBOX_DIR/cat $CONFIG_DIR/env | $BUSYBOX_DIR/xargs)

if [ "$HOSTNAME" ]; then
    $BUSYBOX_DIR/hostname "$HOSTNAME"
fi

# Run guest tools.
distro="runx"
major="1"
minor="2"
uname=$($BUSYBOX_DIR/uname -r)
name="runx"

$BUSYBOX_DIR/cat >/var/cache/xe-linux-distribution <<EOL
os_distro="${distro}"
os_majorver="${major}"
os_minorver="${minor}"
os_uname="${uname}"
os_name="${name}"
EOL

xe_daemon_pid=""
if [ -f "$XE_DAEMON" ]; then
    $XE_DAEMON &
    xe_daemon_pid=$!
fi

# Try to chdir with root user.
working_dir=`$BUSYBOX_DIR/cat $CONFIG_DIR/working_dir`
if [ "$working_dir" ]; then
    cd "$working_dir" &>/dev/null
    if [ $? -eq 0 ]; then
        # Directory changed with success.
        working_dir=""
    fi
fi

# TODO: Change user/group here.

# Retry chdir with new user if necessary.
if [ "$working_dir" ]; then
    cd "$working_dir" &>/dev/null
    if [ $? -ne 0 ]; then
        echo "Failed to change working dir!"
    fi
fi

cmd=`$BUSYBOX_DIR/cat $CONFIG_DIR/cmdline`
echo "Executing $cmd..."
eval $cmd &

if [ "$xe_daemon_pid" ]; then
    $BUSYBOX_DIR/kill $xe_daemon_pid
fi

wait
