#!/run/initramfs/bin/ash

BUSYBOX_DIR=/run/initramfs/bin
CONFIG_DIR=/run/runx

poweroff_handler() {
    $BUSYBOX_DIR/kill -s TERM -1
    $BUSYBOX_DIR/sync
    $BUSYBOX_DIR/sleep 1

    $BUSYBOX_DIR/kill -s KILL -1
    $BUSYBOX_DIR/sync
    $BUSYBOX_DIR/sleep 1

    $BUSYBOX_DIR/umount -a -r
    $BUSYBOX_DIR/swapoff -a
    $BUSYBOX_DIR/poweroff -f
}

trap '' INT
trap poweroff_handler 0 USR1 USR2 TERM

export $($BUSYBOX_DIR/cat $CONFIG_DIR/env | $BUSYBOX_DIR/xargs)

if [ "$HOSTNAME" ]; then
    $BUSYBOX_DIR/hostname "$HOSTNAME"
fi

working_dir=`$BUSYBOX_DIR/cat $CONFIG_DIR/working_dir`
if [ "$working_dir" ]; then
    cd "$working_dir"
fi

cmd=`$BUSYBOX_DIR/cat $CONFIG_DIR/cmdline`
echo "Executing $cmd..."
eval $cmd &
wait
