#!/bin/bash

busybox_path="$1"
if [ -z "$busybox_path" ]; then
    echo "Cannot make initrd, path is empty." >&2
    exit 1
fi

base="`pwd`/initrd"
outpath="$base"/out
tmpdir=`mktemp -d`
tmpfile=`mktemp`
initrd=$outpath/initrd
init="$base"/init-initrd
rm -rf $tmpdir

busybox_src_config="$base"/busybox.config
busybox="$busybox_path/busybox"

rm -rf $outpath
mkdir -p $outpath

cd $busybox_path
cp $busybox_src_config .config
make -j "$(getconf _NPROCESSORS_ONLN)"

mkdir -p $tmpdir/bin
mkdir -p $tmpdir/sbin
mkdir -p $tmpdir/etc
mkdir -p $tmpdir/dev
mkdir -p $tmpdir/proc
mkdir -p $tmpdir/sys
mkdir -p $tmpdir/lib
mkdir -p $tmpdir/var
mkdir -p $tmpdir/mnt
cp "$busybox" $tmpdir/bin/busybox
for i in `cat "$base"/applet-list`
do
    ln -s /bin/busybox $tmpdir/bin/$i
done

cp $init $tmpdir/init # Busybox search a init file at the root when switch_root is called.
chmod +x $tmpdir/init
ln -s -f /init $tmpdir/bin/init # Change default busybox init.

cp "$base"/enter $tmpdir/bin
chmod +x $tmpdir/bin/enter

cd $tmpdir
find . | cpio --create --format='newc' > $tmpfile
gzip < $tmpfile > $initrd
sync

rm -rf $tmpdir
rm -rf $tmpfile
