#!/bin/bash -x

kernel_path="$1"
if [ -z "$kernel_path" ]; then
    echo "Cannot make kernel, path is empty." >&2
    exit 1
fi

if [[ $ARCH = "x86"  ]]
then
    image="bzImage"
elif [[ $ARCH = "arm64" ]]
then
    image="Image.gz"
elif [[ $ARCH = "arm" ]]
then
    image="zImage"
fi

kernel_stuffdir=`readlink -f kernel`
kernel_outpath=$kernel_stuffdir/out
kernel_out=$kernel_outpath/kernel

kernel_src_config="$kernel_stuffdir"/cutdown-config."$ARCH"
kernel_patchesdir="$kernel_stuffdir"/patches
kernel_image="$kernel_path"/arch/"$ARCH"/boot/"$image"

rm -rf $kernel_outpath
mkdir -p $kernel_outpath

old_wd=$(pwd)

cd $kernel_path
cp $kernel_src_config .config
make -j "$(getconf _NPROCESSORS_ONLN)" $image

cd "$old_wd"
cp $kernel_image $kernel_out
