#!/bin/bash

SHUTDOWN_TIMEOUT=30

vm_uuid=$1
vdi_uuid=$2
dir_links="$3/directories"
sr_uuid=$4

if [ "$vm_uuid" ]; then
    timeout $SHUTDOWN_TIMEOUT xe vm-shutdown uuid="$vm_uuid" &>/dev/null
    if [ $? -eq 124 ]; then
        xe vm-shutdown --force uuid="$vm_uuid" &>/dev/null
    fi
fi

if [ "$vdi_uuid" ]; then
    # destroy volume
    rm -f "$dir_links/$vm_uuid"
    xe sr-scan uuid="$sr_uuid"
fi

if [ "$vm_uuid" ]; then
    xe vm-destroy uuid="$vm_uuid"
fi
