#!/bin/bash

SHUTDOWN_TIMEOUT=30

vm_uuid=$1
vdi_uuid=$2

timeout $SHUTDOWN_TIMEOUT xe vm-shutdown uuid="$vm_uuid" &>/dev/null
if [ $? -eq 124 ]; then
    xe vm-shutdown --force uuid="$vm_uuid" &>/dev/null
fi

xe vdi-destroy uuid="$vdi_uuid"
xe vm-destroy uuid="$vm_uuid"
